version: "2"
services:
  #  # OTEL-AGENT
  otel-collector:
    container_name: otel-collector-hano
    image: otel/opentelemetry-collector:0.107.0
    command: ["--config=/etc/otelcol/config.yaml", "--feature-gates=-pkg.translator.prometheus.NormalizeName"]

    volumes:
      - ./otel-agent-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"         # OTLP gRPC receiver
      - "4318:4318"         # OTLP gRPC receiver
  
  # VictoriaMetrics Server
  victoriametrics:
    container_name: victoriametrics-hano
    image: victoriametrics/victoria-metrics:latest
    ports:
      - 8428:8428
      - 4242:4242
    volumes:
      - vmdata:/storage
      #- $PWD/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--storageDataPath=/storage"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
    depends_on:
      - otel-collector


  # Grafana Service
  grafana:
    container_name: grafana-hano
    image: grafana/grafana:8.5.1
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - otel-collector


volumes:
  vmdata: {}
  grafanadata: {}


